#!/bin/sh

# Autostart
pkill -x sxhkd
sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &

# Bspwm settings
bspc config window_gap 10
bspc config border_width 2
bspc monitor -d I II III IV V VI

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#458588"
bspc config normal_border_color "#928374"
bspc config sticky_border_color "#689d6a"
bspc config locked_border_color "#d79921"
bspc config urgent_border_color "#cc241d"
bspc config feedback_color "#3c3836"
